version: '3.9'
services:
  web:
    build:
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_HOST=db
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public_assets:/app/public/assets # Serve precompiled assets
    ports:
      - "3000:3000"

  db:
    environment:
      POSTGRES_DB: app_production

volumes:
  public_assets: