[deploy]
startCommand = "bin/rails db:prepare && bin/rails server -p $PORT -b 0.0.0.0"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
RAILS_ENV = "production"