[build]
builder = "nixpacks"
buildCommand = "bin/rails assets:precompile"

[deploy]
startCommand = "bin/rails db:migrate && bin/rails db:seed && bin/rails server -b 0.0.0.0"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
RAILS_ENV = "production"